#!/bin/sh

LOCK_FILE="$HOME/.cache/eww-calendar.lock"

run() {
  eww open calendar
}

close() {
  eww close calendar
}

if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run
else
    eww close calendar
    rm "$LOCK_FILE"
fi